config/routes.rb
Daysandnights2::Application.routes.draw do
  resources :advertises

  resources :place_types

  resources :types

  resources :places

  resources :events

  get "place/:slug", to: "places#query", as: "slug"

   get "manage/users", to: "user#update"
   get "manage/content", to: "user#content"
   get "manage/admin_content", to: "user#admin_content"
   get "manage", to: "user#manage"

  resources :user do

   post :disapprove, :on => :collection
   post :approve, :on => :collection
   put :complete, :on => :collection
   get "user/:id", to: "user#subscription"
   
  end

  resources :news

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  root "site#index"
  get "contact", to: "site#contact_us"
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get "result", to: "site#result"

  resources :places do
    post :addid, :on => :collection
    post :delid, :on => :collection
  end

  resources :events do
    post :like, :on => :collection
    post :dislike, :on => :collection
  end

   get '404', :to => 'application#404'
   get '422', :to => 'application#404'
   get '500', :to => 'application#404'

end

app/controllers/advertises_controller.rb
class AdvertisesController < ApplicationController
  before_action :set_advertise, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :destroy]

  before_filter :authorize_admin, only: [:show, :new, :edit, :destroy]

  def authorize_admin
    unless current_user.right == 'administrator'
      redirect_to root_path, :notice => "You have no rights to do this"
    end
  end
  # GET /advertises
  # GET /advertises.json
  def index
    @advertises = Advertise.all
  end

  # GET /advertises/1
  # GET /advertises/1.json
  def show
      @advertise = Advertise.find_by_slug!(params[:id])
  end

  # GET /advertises/new
  def new
    @advertise = Advertise.new
  end

  # GET /advertises/1/edit
  def edit
  end

  # POST /advertises
  # POST /advertises.json
  def create
    @advertise = Advertise.new(advertise_params)

    respond_to do |format|
      if @advertise.save
        format.html { redirect_to manage_content_path, notice: 'Advertise was successfully created.' }
        format.json { render action: 'show', status: :created, location: @advertise }
      else
        format.html { render action: 'new' }
        format.json { render json: @advertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertises/1
  # PATCH/PUT /advertises/1.json
  def update
    respond_to do |format|
      if @advertise.update(advertise_params)
        format.html { redirect_to manage_content_path, notice: 'Advertise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @advertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertises/1
  # DELETE /advertises/1.json
  def destroy
    @advertise.destroy
    respond_to do |format|
      format.html { redirect_to manage_content_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertise
      @advertise = Advertise.find_by_slug!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertise_params
      params.require(:advertise).permit(:title, :url, :starts, :advertise_photo, :slug)
    end
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/views/advertises/_form.html.erb
<div class='content-wide'>

<h2>New Advertise</h2>

<%= form_for @advertise, :html => { :multipart => true } do |f|%>
  <% if @advertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertise.errors.count, "error") %> prohibited this advertise from being saved:</h2>
      <ul>
      <% @advertise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new-content-fields">
    <div class="new-content-photo"><%= f.label "Photo" %><%= f.file_field :advertise_photo %></div>
    <div class="new-content-title"><%= f.label "Title" %><%= f.text_field :title %></div>
    <div class="new-content-url"><%= f.label "Url" %><%= f.text_field :url %></div>
    <div class="new-content-starts"><%= f.label "Starts" %><%= f.text_field :starts %></div>
  </div>
  <div class="new-content-links">
  <div class="create-link"><%= f.submit 'Create' %></div>
  <div class="back-link"><%= link_to 'Back', manage_content_path %></div>
  </div>
<% end %>

</div>

<div class="sidebar-right-340">
<div class="sidebar-manage">
<% if  current_user.right == 'administrator' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage user rights', manage_users_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add advertises', new_advertise_path %></div>
<div class="manage-content"><%= link_to 'Add place types', new_place_type_path %></div>
<div class="manage-content"><%= link_to 'Add news', new_news_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'company' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'user' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
</div>
<% end %>
</div>

<div class="search-wrapper">
<h2>SEARCH</h2>
<div class="search-form">
<%= form_tag result_path, :method => :get do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search...", class: "search-input" %>
    <%= submit_tag "Search", :name => nil, :type => :image, :src => "/img/loop.png", class: "search-loop" %>
<% end %>
</div>
</div>

</div>

app/views/advertises/edit.html.erb
<%= render 'form' %>

app/views/advertises/index.html.erb
<h1>Listing advertises</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Starts</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @advertises.each do |advertise| %>
      <tr>
        <td><%= advertise.title %></td>
        <td><%= advertise.url %></td>
        <td><%= advertise.starts %></td>
        <td><%= link_to 'Show', advertise %></td>
        <td><%= link_to 'Edit', edit_advertise_path(advertise) %></td>
        <td><%= link_to 'Destroy', advertise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertise', new_advertise_path %>

app/views/advertises/new.html.erb
<%= render 'form' %>

app/views/advertises/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @advertise.advertise_photo.url(:small) %>

<p>
  <strong>Title:</strong>
  <%= @advertise.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @advertise.url %>
</p>

<p>
  <strong>Starts:</strong>
  <%= @advertise.starts %>
</p>

<%= link_to 'Edit', edit_advertise_path(@advertise) %> |
<%= link_to 'Back', advertises_path %>