config/routes.rb
Daysandnights2::Application.routes.draw do
  resources :advertises

  resources :place_types

  resources :types

  resources :places

  resources :events

  get "place/:slug", to: "places#query", as: "slug"

   get "manage/users", to: "user#update"
   get "manage/content", to: "user#content"
   get "manage/admin_content", to: "user#admin_content"
   get "manage", to: "user#manage"

  resources :user do

   post :disapprove, :on => :collection
   post :approve, :on => :collection
   put :complete, :on => :collection
   get "user/:id", to: "user#subscription"
   
  end

  resources :news

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  root "site#index"
  get "contact", to: "site#contact_us"
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get "result", to: "site#result"

  resources :places do
    post :addid, :on => :collection
    post :delid, :on => :collection
  end

  resources :events do
    post :like, :on => :collection
    post :dislike, :on => :collection
  end

   get '404', :to => 'application#404'
   get '422', :to => 'application#404'
   get '500', :to => 'application#404'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(  profile_name:auth.extra.raw_info.first_name+auth.extra.raw_info.last_name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         gender:auth.extra.raw_info.gender,
                         right:'user',
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  validates :profile_name, presence: true,
  uniqueness: true, format: {
	with: /\A[a-zA-Z0-9_-]*\z/,
	message: 'Must be formatted correctly: no spaces'
  }

  has_many :news
  has_many :place
  has_many :event
  has_many :place_type
  has_many :subscription

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!, only: [:content, :update, :complete]
  before_filter :authorize_company, only: [:content, :update, :complete]
  before_filter :authorize_admin, only: [:update, :admin_content, :complete]


  def authorize_company
    unless current_user.right == "company" or current_user.right == "administrator" 
      redirect_to root_path, :notice => 'You are not authorized'
    end
  end

  def authorize_admin
    unless current_user.right == "administrator" 
      redirect_to root_path, :notice => 'You are not authorized'
    end
  end

  def approve
    @user = User.find_by_profile_name(params[:id])
    Event.where(id: params[:eventid]).update_all(published: 'published')
    @events = Event.all
    redirect_to user_path(current_user.profile_name) 
  end

  def disapprove
    @user = User.find_by_profile_name(params[:id])
    Event.where(id: params[:eventid]).update_all(published: 'waiting')
    @events = Event.all
    redirect_to user_path(current_user.profile_name) 
  end


  def complete
    User.where(:id => params[:complete_users]).update_all(right: "user")
    User.where(:id => params[:complete_companies]).update_all(right: "company")
    User.where(:id => params[:complete_admins]).update_all(right: "administrator")
    redirect_to manage_users_path
  end


  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @subscriptions = Subscription.where(user_id: @user.id)
      @events = Event.all
      @places = Place.all.limit(2).order("RANDOM()")
      render action: :subscription
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end

  def content
    @news = News.all
    @users = User.all
    @places = Place.all
    @events = Event.all
    @advertises = Advertise.all
    if user_signed_in?
    @users.each do |usr|
      if usr.id == current_user.id
        @user_name = usr.profile_name
        @user_id = usr.id
        @user_right = usr.right
      end
    end
    else
    render :file => "/app/views/places/index.html.erb",  :status => 'subscribed'
    end    
  end

  def update
    @user = User.all
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def user_params
      params.require(:user).permit(:id, :right)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/admin_content.html.erb
<div class='content-wide'>

<h2><%= current_user.profile_name %></h2>

<% if current_user.id == @user.id %>
<% if current_user.right == 'administrator' %>
<div class="admin-show-content-head">
<div class="admin-show-content-head-title">Title</div>
<div class="admin-show-content-head-type">Type</div>
<div class="admin-show-content-head-edit">Edit</div>
<div class="admin-show-content-head-delete">Delete</div>
</div>
<div class="admin-show-content">
<% if @news %>
    <% @news.each do |news| %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= news.title %></div>
        <div class="admin-content-type">News</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_news_path(news), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', news, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
    <% end %>
<% end %>

<% if @places %>
    <% @places.each do |place| %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= place.title %></div>
        <div class="admin-content-type">Place</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_place_path(place), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', place, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
   <% end %>
<% end %>

<% if @events %>
    <% @events.each do |event| %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= event.title %></div>
        <div class="admin-content-type">Event</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_event_path(event), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
   <% end %>
<% end %>

<% if @advertises %>
    <% @advertises.each do |adv| %>
        <div class="admin-content-each">      
        <div class="admin-content-title"><%= adv.title %></div>
        <div class="admin-content-type">Advertise</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_advertise_path(adv), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', adv, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
   <% end %>
<% end %>
</div>
<% end %>
<% end %>
</div>

<div class="sidebar-right-340">
<div class="sidebar-manage">
<% if  current_user.right == 'administrator' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage user rights', manage_users_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add advertises', new_advertise_path %></div>
<div class="manage-content"><%= link_to 'Add place types', new_place_type_path %></div>
<div class="manage-content"><%= link_to 'Add news', new_news_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'company' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'user' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
</div>
<% end %>
</div>

<div class="search-wrapper">
<h2>SEARCH</h2>
<div class="search-form">
<%= form_tag result_path, :method => :get do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search...", class: "search-input" %>
    <%= submit_tag "Search", :name => nil, :type => :image, :src => "/img/loop.png", class: "search-loop" %>
<% end %>
</div>
</div>

</div>

app/views/user/content.html.erb
<div class='content-wide'>
<h2><%= current_user.profile_name %></h2>

<% if current_user.id == @user_id %>
<% if current_user.right == 'administrator' %>
<div class="admin-show-content-head">
<div class="admin-show-content-head-title">Title</div>
<div class="admin-show-content-head-type">Type</div>
<div class="admin-show-content-head-edit">Edit</div>
<div class="admin-show-content-head-delete">Delete</div>
</div>
<div class="admin-show-content">
<% if @news %>
    <% @news.each do |news| %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= link_to news.title, news_path(news) %></div>
        <div class="admin-content-type">News</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_news_path(news), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', news, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
    <% end %>
<% end %>

<% if @places %>
    <% @places.each do |place| %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= link_to place.title, place_path(place) %></div>
        <div class="admin-content-type">Place</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_place_path(place), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', place, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
   <% end %>
<% end %>

<% if @events %>
    <% @events.each do |event| %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= link_to event.title, event_path(event) %></div>
        <div class="admin-content-type">Event</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_event_path(event), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
   <% end %>
<% end %>

<% if @advertises %>
    <% @advertises.each do |adv| %>
        <div class="admin-content-each">      
        <div class="admin-content-title"><%= link_to adv.title, advertise_path(adv) %></div>
        <div class="admin-content-type">Advertise</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_advertise_path(adv), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', adv, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
   <% end %>
<% end %>
</div>
<% end %>

<% if current_user.right == 'company' %>
<div class="admin-show-content-head">
<div class="admin-show-content-head-title">Title</div>
<div class="admin-show-content-head-type">Type</div>
<div class="admin-show-content-head-edit">Edit</div>
<div class="admin-show-content-head-delete">Delete</div>
</div>
<div class="admin-show-content">

<% if @places %>
    <% @places.each do |place| %>
      <% if place.user_id == current_user.id %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= link_to place.title, place_path(place) %></div>
        <div class="admin-content-type">Place</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_place_path(place), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', place, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
     <% end %>
   <% end %>
<% end %>

<% if @events %>
    <% @events.each do |event| %>
      <% if event.user_id == current_user.id %>
        <div class="admin-content-each">
        <div class="admin-content-title"><%= link_to event.title, event_path(event) %></div>
        <div class="admin-content-type">Event</div>
        <div class="content-edit-link"><%= link_to 'edit', edit_event_path(event), class: 'content-edit' %></div>
        <div class="content-delete-link"><%= link_to 'delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'content-delete' %></div>
        </div>
     <% end %>
   <% end %>
<% end %>

</div>
<% end %>


<% end %>
</div>

<div class="sidebar-right-340">
<div class="sidebar-manage">
<% if  current_user.right == 'administrator' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage user rights', manage_users_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add advertises', new_advertise_path %></div>
<div class="manage-content"><%= link_to 'Add place types', new_place_type_path %></div>
<div class="manage-content"><%= link_to 'Add news', new_news_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'company' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'user' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
</div>
<% end %>
</div>

<div class="search-wrapper">
<h2>SEARCH</h2>
<div class="search-form">
<%= form_tag result_path, :method => :get do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search...", class: "search-input" %>
    <%= submit_tag "Search", :name => nil, :type => :image, :src => "/img/loop.png", class: "search-loop" %>
<% end %>
</div>
</div>

</div>

app/views/user/manage.html.erb
<% if  current_user.right == 'administrator' %>
<h3><%= link_to 'Manage user rights', manage_users_path %> </h3>
<h3><%= link_to 'Manage content', manage_admin_content_path %> </h3>
<h3><%= link_to 'Add advertises', new_advertise_path %> </h3>
<h3><%= link_to 'Add place types', new_place_type_path %> </h3>
<h3><%= link_to 'Add news', new_news_path %> </h3>
<% end %>
<h3><%= link_to 'Add places', new_place_path %> </h3>
<h3><%= link_to 'Add events', new_event_path %> </h3>

app/views/user/subscription.html.erb
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCtT4b7ISSx0uBy3pCEiJ1ulQ-NQG4Th_E&sensor=false"></script>

<div class='content-wide'>

<h2><%= @user.profile_name %></h2>
<% if user_signed_in? %>
<% if current_user.right == 'user' %>
<% if @subscriptions %>

    <div class="subscription-head">
      <div class="subscription-head-title">Title</div>
      <div class="subscription-head-type">Type</div>
      <div class="subscription-head-male">Male</div>
      <div class="subscription-head-female">Female</div>
      <div class="subscription-head-address">Address</div>
      <div class="subscription-head-status">Status</div>
    </div>

  <% @subscriptions.each do |subscription| %>
    <div class="subscription-body">
      <div class="subscription-title"><%= subscription.place.title %></div>
      <div class="subscription-place-type"><% @placetype = PlaceType.find_by_id(subscription.place.place_type_id) %><%= @placetype.title %></div>
      <div class="subscription-male-count"><%= subscription.place.subscribers_male %></div>
      <div class="subscription-female-count"><%= subscription.place.subscribers_female %></div>
      <div id="<%= subscription.place.id %>" class="subscription-place-gmap"></div>
      <div class="subscription-subscribe-button">
      <% if user_signed_in? %>
        <% if Subscription.exists?(user_id: current_user.id, place_id: subscription.place.id) %>
          <%= link_to "unsubscribe",
 				     {:controller => :places, 
                                     :action => 'delid',
                                     :plid => subscription.place.id},
                                     {:class => 'unsub subactive',
				     :value => subscription.place.id} %>
          <%= link_to "subscribe",
 				     {:controller => :places, 
                                     :action => 'addid',
                                     :plid => subscription.place.id},
                                     {:class => 'sub subpassive',
				     :value => subscription.place.id} %>

        <% else %>
          <%= link_to "subscribe",
 				     {:controller => :places, 
                                     :action => 'addid',
                                     :plid => subscription.place.id},
                                     {:class => 'sub subactive',
				     :value => subscription.place.id} %>
          <%= link_to "unsubscribe",
 				     {:controller => :places, 
                                     :action => 'delid',
                                     :plid => subscription.place.id},
                                     {:class => 'unsub subpassive',
				     :value => subscription.place.id} %>

        <% end %>
      <% else %>
        <%= button_to "subscribe", user_session_path %>
      <% end %>
      </div>
<script type="text/javascript">
          var readys;
          readys = function initialize() {
           var myLatlng = new google.maps.LatLng(<%= subscription.place.latitude %>, <%= subscription.place.longitude %>); 
           var mapOptions = {
              zoom: 16,
              center: myLatlng
            };
            var map = new google.maps.Map(document.getElementById("map-canvas-<%= subscription.place.id %>"),
                mapOptions);
            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: '<%= subscription.place.title %>'
            });
            };

          
           $(document).ready(readys);
           $(document).on('page:load', readys);
</script>
        <div class="subscription-place-content"><%= subscription.place.content %></div>
        <div id="map-wrapper-<%= subscription.place.id %>">
        <div class="map-title">MAP DISTANCE</div>
        <div class="map-close">CLOSE</div>
        <div id="map-canvas-<%= subscription.place.id %>"></div>
        </div>
        </div>
  <% end %>
<% else %>
  No subscriptions... yet
<% end %>
<div id="map-background"> </div>
<% end %>

<% if current_user.id == @user.id %>
<% if current_user.right == 'company' or current_user.right == 'administrator' %>

<div class="admin-show-content-head">
<div class="admin-show-content-head-username">Username</div>
<div class="admin-show-content-head-event">Event name</div>
<div class="admin-show-content-head-status">Status</div>
<div class="admin-show-content-head-action">Action</div>
</div>

  <% @events.each do |event| %>
    <% @curplace = Place.find_by(id: event.place_id) %>
     <% if @user.id == @curplace.user_id %>
       <% @creator = User.find_by(id: event.user_id) %>
         <% if @user.id != @creator.id  %> 
    
        <div class="admin-content-each">
        <div class="admin-content-username"><%= @creator.profile_name %></div>
        <div class="admin-content-event"><%= truncate(event.title, :length => 25) %></div>
        <div class="admin-content-status"><%= event.published %></div>
        <% if event.published == "waiting" %>
          <div class="admin-content-action"><%= button_to "approve", :controller => :user, 
                                                                     :action => 'approve',
                                                                     :eventid => event.id,
                                                                     :method => :post %></div>
       <% else %>
         <div class="admin-content-action"><%= button_to "disapprove", :controller => :user, 
                                                                       :action => 'disapprove',
                                                                       :eventid => event.id,
                                                                       :method => :post %></div>
       <% end %>

       </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<% end %>
<% end %>
</div>

<div class="sidebar-right-340">
<div class="sidebar-manage">
<% if user_signed_in? %>
<% if current_user.right == 'user' %>
<h2>PLACES</h2>
<div class="sidebar-right-wrapper">
  <% @places.each do |place| %>
        <div class="sidebar-right-img"><%= link_to image_tag(place.place_photo(:sidebar)), place %></div>
  <% end %>
</div>

<% end %>
<div class="sidebar-manage">
<% if  current_user.right == 'administrator' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage user rights', manage_users_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add advertises', new_advertise_path %></div>
<div class="manage-content"><%= link_to 'Add place types', new_place_type_path %></div>
<div class="manage-content"><%= link_to 'Add news', new_news_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'company' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'user' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
</div>
<% end %>
</div>

<% end %>
</div>

<div class="search-wrapper">
<h2>SEARCH</h2>
<div class="search-form">
<%= form_tag result_path, :method => :get do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search...", class: "search-input" %>
    <%= submit_tag "Search", :name => nil, :type => :image, :src => "/img/loop.png", class: "search-loop" %>
<% end %>
</div>
</div>

</div>

app/views/user/update.html.erb
<div class='content-wide'>

<h2><%= current_user.profile_name %></h2>

<div class="admin-show-content-head">
<div class="admin-show-content-head-name">Username</div>
<div class="admin-show-content-head-right">Right</div>
<div class="admin-show-content-head-edit-right">Edit</div>
</div>

<%= form_tag complete_user_index_path, :method => :put do %>
<% if @user %>

  <% @user.each do |user| %>
    <div class="admin-content-each">
    <div class="admin-content-name"><%= user.profile_name %></div>
    <div class="admin-content-right"><%= user.right %></div>
    <div class="admin-content-edit-right">
      <%= check_box_tag "complete_users[]", user.id %>
    User
      <%= check_box_tag "complete_companies[]", user.id %>
    Company
      <%= check_box_tag "complete_admins[]", user.id %>
    Administrator
    </div>
    </div>
  <% end %>
<% end %>
  <div class="actions">
       <%= submit_tag 'Update', class: "update-rights-button" %>
  </div>
<% end %>
</div>

<div class="sidebar-right-340">
<div class="sidebar-manage">
<% if  current_user.right == 'administrator' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage user rights', manage_users_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add advertises', new_advertise_path %></div>
<div class="manage-content"><%= link_to 'Add place types', new_place_type_path %></div>
<div class="manage-content"><%= link_to 'Add news', new_news_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'company' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'user' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
</div>
<% end %>
</div>

<div class="search-wrapper">
<h2>SEARCH</h2>
<div class="search-form">
<%= form_tag result_path, :method => :get do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search...", class: "search-input" %>
    <%= submit_tag "Search", :name => nil, :type => :image, :src => "/img/loop.png", class: "search-loop" %>
<% end %>
</div>
</div>

</div>