config/routes.rb
Daysandnights2::Application.routes.draw do
  resources :advertises

  resources :place_types

  resources :types

  resources :places

  resources :events

  get "place/:slug", to: "places#query", as: "slug"

   get "manage/users", to: "user#update"
   get "manage/content", to: "user#content"
   get "manage/admin_content", to: "user#admin_content"
   get "manage", to: "user#manage"

  resources :user do

   post :disapprove, :on => :collection
   post :approve, :on => :collection
   put :complete, :on => :collection
   get "user/:id", to: "user#subscription"
   
  end

  resources :news

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  root "site#index"
  get "contact", to: "site#contact_us"
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get "result", to: "site#result"

  resources :places do
    post :addid, :on => :collection
    post :delid, :on => :collection
  end

  resources :events do
    post :like, :on => :collection
    post :dislike, :on => :collection
  end

   get '404', :to => 'application#404'
   get '422', :to => 'application#404'
   get '500', :to => 'application#404'

end

app/controllers/place_types_controller.rb
class PlaceTypesController < ApplicationController
  before_action :set_place_type, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :destroy]

  before_filter :authorize_user, only: [:show, :new, :edit, :destroy]
  def authorize_user
    unless current_user.right == "administrator" 
      redirect_to root_path, :notice => 'You are not authorized'
    end
  end

  # GET /place_types
  # GET /place_types.json
  def index
    @place_types = PlaceType.all
  end

  # GET /place_types/1
  # GET /place_types/1.json
  def show
  end

  # GET /place_types/new
  def new
    @place_type = PlaceType.new
  end

  # GET /place_types/1/edit
  def edit
  end

  # POST /place_types
  # POST /place_types.json
  def create
    @place_type = PlaceType.new(place_type_params)

    respond_to do |format|
      if @place_type.save
        format.html { redirect_to manage_content_path, notice: 'Place type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @place_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_types/1
  # PATCH/PUT /place_types/1.json
  def update
    respond_to do |format|
      if @place_type.update(place_type_params)
        format.html { redirect_to manage_content_path, notice: 'Place type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_types/1
  # DELETE /place_types/1.json
  def destroy
    @place_type.destroy
    respond_to do |format|
      format.html { redirect_to manage_content_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_type
      @place_type = PlaceType.find_by_slug!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_type_params
      params.require(:place_type).permit(:title, :slug, :category)
    end
end

app/helpers/place_types_helper.rb
module PlaceTypesHelper
end

app/views/place_types/_form.html.erb
<div class='content-wide'>

<h2>New Place type</h2>

<%= form_for(@place_type) do |f| %>
  <% if @place_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place_type.errors.count, "error") %> prohibited this place_type from being saved:</h2>

      <ul>
      <% @place_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% @categories = ["i need", "socialising", "sporting", "developing", "shopping"] %>

  <div class="new-content-fields">
    <div class="new-content-title"><%= f.label "Title" %><%= f.text_field :title %></div>
    <div class="new-content-category"><%= f.label "Category" %><%= f.select(:category, @categories) %></div>
  </div>

  <div class="new-content-links">
    <div class="create-link"><%= f.submit 'Create' %></div>
    <div class="back-link"><%= link_to 'Back', manage_content_path %></div>
  </div>
<% end %>

</div>

<div class="sidebar-right-340">
<div class="sidebar-manage">
<% if  current_user.right == 'administrator' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage user rights', manage_users_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add advertises', new_advertise_path %></div>
<div class="manage-content"><%= link_to 'Add place types', new_place_type_path %></div>
<div class="manage-content"><%= link_to 'Add news', new_news_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'company' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Your account', user_path(:id => current_user.profile_name) %></div>
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
<div class="manage-content"><%= link_to 'Manage content', manage_content_path %></div>
<div class="manage-content"><%= link_to 'Add places', new_place_path %></div>
<div class="manage-content"><%= link_to 'Add events', new_event_path %></div>
</div>
<% end %>
<% if current_user.right == 'user' %>
<h2>MANAGE</h2>
<div class="manage-content-wrapper">
<div class="manage-content"><%= link_to 'Edit account', edit_user_registration_path %></div>
</div>
<% end %>
</div>

<div class="search-wrapper">
<h2>SEARCH</h2>
<div class="search-form">
<%= form_tag result_path, :method => :get do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search...", class: "search-input" %>
    <%= submit_tag "Search", :name => nil, :type => :image, :src => "/img/loop.png", class: "search-loop" %>
<% end %>
</div>
</div>

</div>

app/views/place_types/edit.html.erb
<%= render 'form' %>

app/views/place_types/index.html.erb
<h1>Listing place_types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @place_types.each do |place_type| %>
      <tr>
        <td><%= place_type.title %></td>
        <td><%= link_to 'Show', place_type %></td>
        <td><%= link_to 'Edit', edit_place_type_path(place_type) %></td>
        <td><%= link_to 'Destroy', place_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place type', new_place_type_path %>

app/views/place_types/new.html.erb
<%= render 'form' %>

app/views/place_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @place_type.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @place_type.slug %>
</p>

<%= link_to 'Edit', edit_place_type_path(@place_type) %> |
<%= link_to 'Back', place_types_path %>