config/routes.rb
Daysandnights2::Application.routes.draw do
  resources :advertises

  resources :place_types

  resources :types

  resources :places

  resources :events

  get "place/:slug", to: "places#query", as: "slug"

   get "manage/users", to: "user#update"
   get "manage/content", to: "user#content"
   get "manage/admin_content", to: "user#admin_content"
   get "manage", to: "user#manage"

  resources :user do

   post :disapprove, :on => :collection
   post :approve, :on => :collection
   put :complete, :on => :collection
   get "user/:id", to: "user#subscription"
   
  end

  resources :news

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  root "site#index"
  get "contact", to: "site#contact_us"
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get "result", to: "site#result"

  resources :places do
    post :addid, :on => :collection
    post :delid, :on => :collection
  end

  resources :events do
    post :like, :on => :collection
    post :dislike, :on => :collection
  end

   get '404', :to => 'application#404'
   get '422', :to => 'application#404'
   get '500', :to => 'application#404'

end

app/models/ability.rb
class Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/advertise.rb
class Advertise < ActiveRecord::Base
  before_create :create_slug

  def to_param
    slug
  end
    
  def create_slug
    self.slug = self.title.parameterize
  end

  belongs_to :user

  validates :title, uniqueness: true

  has_attached_file :advertise_photo, :styles => { :small => "100x120#", :medium => "240x280#" },
                  :url  => "/assets/advertise/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/advertise/:id/:style/:basename.:extension"

  validates_attachment_presence :advertise_photo
  validates_attachment_size :advertise_photo, :less_than => 5.megabytes
  validates_attachment_content_type :advertise_photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/event.rb
class Event < ActiveRecord::Base
  before_create :create_slug
  
  def to_param
    slug
  end
    
  def create_slug
    self.slug = self.title.parameterize
  end

  belongs_to :user
  belongs_to :place

  validates :title, uniqueness: true

  has_attached_file :event_photo, :styles => { :small => "200x200#", :sidebar => "290x150#", :medium => "370x225#", :large => "600x400" },
                  :url  => "/assets/events/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/events/:id/:style/:basename.:extension"

  validates_attachment_presence :event_photo
  validates_attachment_size :event_photo, :less_than => 30.megabytes
  validates_attachment_content_type :event_photo, :content_type => ['image/jpeg', 'image/png']

  searchable do
    text :title, :content, :start_date
  end

end

app/models/job.rb
class Job < ActiveRecord::Base

belongs_to :place

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :place

end

app/models/message.rb
class Message

 extend ActiveModel::Naming
 include ActiveModel::Conversion
 include ActiveModel::Validations
 include ActionView::Helpers::TextHelper

  attr_accessor :name, :email, :position, :comment, :form_sender

  validates :name, :email, :comment, :form_sender, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  before_create :create_slug
  
  def to_param
    slug
  end
    
  def create_slug
    self.slug = self.title.parameterize
  end

  validates :title, uniqueness: true

  belongs_to :user

  searchable do
    text :title, :content
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  before_create :create_slug
 
  geocoded_by :address
  after_validation :geocode
   
  def to_param
    slug
  end
    
  def create_slug
    self.slug = self.title.parameterize
  end

  validates :title, uniqueness: true



  has_attached_file :place_photo, :styles => { :small => "200x200#", :sidebar => "290x150#", :medium => "370x225#", :large => "600x400" },
                  :url  => "/assets/places/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/places/:id/:style/:basename.:extension"

  validates_attachment_presence :place_photo
  validates_attachment_size :place_photo, :less_than => 5.megabytes
  validates_attachment_content_type :place_photo, :content_type => ['image/jpeg', 'image/png']

  belongs_to :user
  belongs_to :place_type
  has_many :subscription
  has_many :like
  has_many :jobs
  has_many :place_galleries, :dependent => :destroy
  accepts_nested_attributes_for :place_galleries, :jobs, :allow_destroy => true

  searchable do
    text :title, :content
  end

end

app/models/place_gallery.rb
class PlaceGallery < ActiveRecord::Base

belongs_to :place
has_attached_file :image,
    :styles => {
 :small => "190x100#", :large => "800x600>" 
        },
                  :url  => "/assets/place_galleries/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/place_galleries/:id/:style/:basename.:extension"
end

app/models/place_type.rb
class PlaceType < ActiveRecord::Base
  before_create :create_slug
  
  def to_param
    slug
  end
    
  def create_slug
    self.slug = self.title.parameterize
  end

  validates :title, uniqueness: true

  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :place

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(  profile_name:auth.extra.raw_info.first_name+auth.extra.raw_info.last_name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         gender:auth.extra.raw_info.gender,
                         right:'user',
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  validates :profile_name, presence: true,
  uniqueness: true, format: {
	with: /\A[a-zA-Z0-9_-]*\z/,
	message: 'Must be formatted correctly: no spaces'
  }

  has_many :news
  has_many :place
  has_many :event
  has_many :place_type
  has_many :subscription

end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daysandnights</title>
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <% @hour = Time.now %>
  <% if @hour.hour > 18 %>
  <%= stylesheet_link_tag    "application-nights", media: "all" %>
  <% else if @hour.hour < 7%>
  <%= stylesheet_link_tag    "application-nights", media: "all" %>
  <% else %>
  <%= stylesheet_link_tag    "application-days", media: "all" %>
  <% end %>
  <% end %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page">
<header>
<% if @hour.hour > 18 %>
<%= link_to image_tag('/img/logo_night.png'), root_path, class: 'logo' %>
<% else if @hour.hour < 7%>
<%= link_to image_tag('/img/logo_night.png'), root_path, class: 'logo' %>
<% else %>
<%= link_to image_tag('/img/logo_day.png'), root_path, class: 'logo' %>
<% end %>
<% end %>

<div class="sign-window-back"></div>
<div class="login">
  <% if user_signed_in? %>
    <%= link_to current_user.profile_name, user_path(current_user.profile_name), class: "user-link" %>
    <%= link_to "LOG OUT", destroy_user_session_path , method: :delete, class: "logout-link"%>
  <% else %>
    <div class="login-link" id="login-link"><%= link_to_modal "LOGIN", new_user_session_path %></div>
    <div class="register-link" id="register-link"><%= link_to_modal "REGISTER", new_user_registration_path %></div> 
  <% end %>
</div>
</header>
<nav class="menu">
    <ul>
    <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Welcome", root_path %></li>
    <li class="<%= 'active' if current_page?(news_index_path) or (params[:controller]=='news' and params[:action] == 'show') %>"><%= link_to "News", news_index_path %></li>
    <li class="<%= 'active' if current_page?(places_path) or (params[:controller]=='places' and params[:action] == 'query') or (params[:controller]=='places' and params[:action] == 'show') %>"><%= link_to "Places", places_path %>
    <ul>
    <% @types = PlaceType.all %>
    <% @types.group_by(&:category).each do |category, type| %>
    <li><%= category %>
    <ul>
    <% type.each do |t|%>
    <li><%= link_to t.title, :controller => '/places', :action => "query", :slug => t.slug %></li>
    <% end %>
    </ul></li>
    <% end %>
    </ul>
    </li>
    <li class="<%= 'active' if current_page?(events_path) or (params[:controller]=='events' and params[:action] == 'show') %>"><%= link_to "Events", events_path %></li>
    <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "About", contact_path %></li>
    <ul>
</nav>
<div id="content">
  <% if !notice.nil? %>
    <div class="notice midway-horizontal midway-vertical"><%= notice %></div>
    <div class="flash-bg" style="z-index: 5; opacity: 0.5;"></div>
  <% end %>
  <% if !alert.nil? %>
    <div class="alert midway-horizontal midway-vertical"><%= alert %></div>
    <div class="flash-bg" style="z-index: 5; opacity: 0.5;"></div>
  <% end %>
<%= yield %>
</div>
</div>
<footer>
<div class="copyright">2013 © Days&Nights</div>
<div class="logo-footer"></div>
</footer>
</body>
</html>